<a href="https://colab.research.google.com/github/neto-riga/metodos_numericos_2/blob/main/13_diferencias_finitas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [Regresar al ínidce](https://github.com/neto-riga/metodos_numericos_2/blob/main/portafolio.md#índice)

# Ejercicio 13. Diferencias finitas
---

Sea la función:
$$
f(x) = 4xln(x) + \frac{\cos(x-3)}{\sqrt{1+x^2}}
$$

* Estimar la derivada para $x=1.5$ con $h=0.1$, $0.05$ y $0.025$ empleando la fórmula de diferencia centrada.
* Tabular la función en el intervalo $[0.5,2.3]$ con intervalor de $h=0.1$ y estimar la derivada en cada punto, para $[0.6,2.2]$.
* Para los incisos anteriores comparar con la solución analítica.

In [ ]:
import numpy as np 
import pandas as pd 
import math
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

Declaramos la función para llenar listas.

In [ ]:
def Listas (val,h,n):
  f = lambda x: (4*x*np.log(x)) + ((np.cos(x-3))/(np.sqrt(1 + x**2)))
  x = [val - h]
  fx = [f(x[0])]
  for i in range(n):
    x.append(x[i]+h)
    i+=1
    fx.append(f(x[i]))
  return x,fx

Definimos las diferencias centradas.

In [ ]:
def Dife_cen(x,fx,h):
  dif = []
  for i in range(len(x)-2):
    dif.append((1/(2*h)) * (fx[i+2]-fx[i]))
  return dif

Tabulamos para las diferentes $h$

In [ ]:
h = [0.1,0.05,0.025]
val = 1.5
x1,fx1 = Listas(val,h[0],2)
tabla1 = {'x': x1, 'f(x)': fx1}
print(f'Para h={h[0]}: \n')
df1 = pd.DataFrame(tabla1)
display(df1)
x2,fx2 = Listas(val,h[1],2)
tabla2 = {'x': x2, 'f(x)': fx2}
print(f'Para h={h[1]}: \n')
df2 = pd.DataFrame(tabla2)
display(df2)
x3,fx3 = Listas(val,h[2],2)
tabla3 = {'x': x3, 'f(x)': fx3}
print(f'Para h={h[2]}: \n')
df3 = pd.DataFrame(tabla3)
display(df3)

Para h=0.1:

     x      f(x)
0  1.4  1.867273
1  1.5  2.472029
2  1.6  3.098106

Para h=0.05:

      x      f(x)
0  1.45  2.166875
1  1.50  2.472029
2  1.55  2.782508

Para h=0.025:

       x      f(x)
0  1.475  2.318772
1  1.500  2.472029
2  1.525  2.626616

Declaramos $f'(x)$

In [ ]:
def D(x):
  r = (4*np.log(x)) + 4 
  z = (((1+x**2)*(-np.sin(x-3))) - (x*np.cos(x-3))) / ((1+x**2)**(3/2))
  return r+z

Aproximamos a la derivadas.

In [ ]:
Sol=[]
Sol.append(Dife_cen(x1,fx1,h[0]))
Sol.append(Dife_cen(x2,fx2,h[1]))
Sol.append(Dife_cen(x3,fx3,h[2]))
Err=[]
for i in range(len(Sol)):
  Err.append(abs(D(val) - Sol[i]))
tabla4 = {'h': h,
          'Dif. centrada': Sol,
          'Error absoluto': Err
}
df4 = pd.DataFrame(tabla4)
df4

       h        Dif. centrada            Error absoluto
0  0.100  [6.154164926331372]   [0.0028963526063146006]
1  0.050  [6.156338245727082]   [0.0007230332106047399]
2  0.025  [6.156880586420614]  [0.00018069251707242273]

Tabulamos la función en el intervalo $[0.5,2.3]$ con $h=0.1$

In [ ]:
x4,fx4 = Listas(0.6,0.1,18)
tabla5 = {'x': x4, 'f(x)': fx4}
df5 = pd.DataFrame(tabla5)
df5

      x      f(x)
0   0.5 -2.102859
1   0.6 -1.858291
2   0.7 -1.544524
3   0.8 -1.173602
4   0.9 -0.754547
5   1.0 -0.294260
6   1.1  0.201897
7   1.2  0.729692
8   1.3  1.285736
9   1.4  1.867273
10  1.5  2.472029
11  1.6  3.098106
12  1.7  3.743899
13  1.8  4.408040
14  1.9  5.089350
15  2.0  5.786808
16  2.1  6.499525
17  2.2  7.226724
18  2.3  7.967726

Apriximamos la derivada y obtenemos el error absoluto del intervalo $[0.6,2.2]$

In [ ]:
lis = Dife_cen(x4,fx4,0.1)
Err2=[]
for i in range(len(lis)):
  Err2.append(abs(D(x4[1:-1][i]) - lis[i]))

tabla6={'x': x4[1:-1], 'Dif. Centrada': lis, 'Error abs': Err2}
df6 = pd.DataFrame(tabla6)
df6

      x  Dif. Centrada  Error abs
0   0.6       2.791673   0.023190
1   0.7       3.423449   0.017189
2   0.8       3.949887   0.013035
3   0.9       4.396706   0.010058
4   1.0       4.782219   0.007882
5   1.1       5.119762   0.006271
6   1.2       5.419198   0.005064
7   1.3       5.687902   0.004148
8   1.4       5.931461   0.003445
9   1.5       6.154165   0.002896
10  1.6       6.359354   0.002461
11  1.7       6.549674   0.002111
12  1.8       6.727255   0.001823
13  1.9       6.893838   0.001584
14  2.0       7.050872   0.001382
15  2.1       7.199580   0.001209
16  2.2       7.341009   0.001059

## [Regresar al ínidce](https://github.com/neto-riga/metodos_numericos_2/blob/main/portafolio.md#índice)